### ISSUE TITLE
Provide more information about cause of exception during Excel import 

### ISSUE THREAD

**Issue by Evertude** [protegeproject/cellfie-plugin#113]
I get the following exception when I load an excel sheet with Cellfie 2.1.0 into Protege 5.2.0: 
java.lang.IllegalStateException: Cannot get a numeric value from a text cell

It would be really useful to know which cell had a problem because I'm parsing a huge excel sheet and I have no clue what causes the problem.

Stack trace
```
java.lang.IllegalStateException: Cannot get a numeric value from a text cell
        at org.apache.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:895
)
        at org.apache.poi.xssf.usermodel.XSSFCell.getNumericCellValue(XSSFCell.j
ava:216)
        at org.mm.cellfie.ui.view.SheetPanel$SheetTableModel.getValueAt(SheetPan
el.java:164)
        at javax.swing.JTable.getValueAt(JTable.java:2717)
        at javax.swing.JTable.prepareRenderer(JTable.java:5706)
        at org.mm.cellfie.ui.view.SheetTable.resizeColumnWidth(SheetTable.java:5
0)
        at org.mm.cellfie.ui.view.SheetTable.<init>(SheetTable.java:39)
        at org.mm.cellfie.ui.view.SheetPanel.<init>(SheetPanel.java:60)
        at org.mm.cellfie.ui.view.DataSourceView.<init>(DataSourceView.java:39)
        at org.mm.cellfie.ui.view.WorkspacePanel.<init>(WorkspacePanel.java:100)

        at org.mm.cellfie.ui.view.WorkspacePanel.createDialog(WorkspacePanel.jav
a:274)
        at org.mm.cellfie.action.CellfieAction.showCellfieDialog(CellfieAction.j
ava:53)
        at org.mm.cellfie.action.CellfieAction.actionPerformed(CellfieAction.jav
a:41)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:20
22)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.jav
a:2346)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel
.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259
)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:8
33)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMen
uItemUI.java:877)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:2
89)
        at java.awt.Component.processMouseEvent(Component.java:6525)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6290)
        at java.awt.Container.processEvent(Container.java:2234)
        at java.awt.Component.dispatchEventImpl(Component.java:4881)
        at java.awt.Container.dispatchEventImpl(Container.java:2292)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898
)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)

        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
        at java.awt.Container.dispatchEventImpl(Container.java:2278)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:702)
        at java.awt.EventQueue$3.run(EventQueue.java:696)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDo
main.java:75)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDo
main.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:724)
        at java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDo
main.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThre
ad.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.IllegalStateException: Cannot get a numeric value from a text cell
        at org.apache.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:895
)
        at org.apache.poi.xssf.usermodel.XSSFCell.getNumericCellValue(XSSFCell.j
ava:216)
        at org.mm.cellfie.ui.view.SheetPanel$SheetTableModel.getValueAt(SheetPan
el.java:164)
        at javax.swing.JTable.getValueAt(JTable.java:2717)
        at javax.swing.JTable.prepareRenderer(JTable.java:5706)
        at org.mm.cellfie.ui.view.SheetTable.resizeColumnWidth(SheetTable.java:5
0)
        at org.mm.cellfie.ui.view.SheetTable.<init>(SheetTable.java:39)
        at org.mm.cellfie.ui.view.SheetPanel.<init>(SheetPanel.java:60)
        at org.mm.cellfie.ui.view.DataSourceView.<init>(DataSourceView.java:39)
        at org.mm.cellfie.ui.view.WorkspacePanel.<init>(WorkspacePanel.java:100)

        at org.mm.cellfie.ui.view.WorkspacePanel.createDialog(WorkspacePanel.jav
a:274)
        at org.mm.cellfie.action.CellfieAction.showCellfieDialog(CellfieAction.j
ava:53)
        at org.mm.cellfie.action.CellfieAction.actionPerformed(CellfieAction.jav
a:41)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:20
22)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.jav
a:2346)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel
.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259
)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:8
33)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMen
uItemUI.java:877)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:2
89)
        at java.awt.Component.processMouseEvent(Component.java:6525)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6290)
        at java.awt.Container.processEvent(Container.java:2234)
        at java.awt.Component.dispatchEventImpl(Component.java:4881)
        at java.awt.Container.dispatchEventImpl(Container.java:2292)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898
)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)

        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
        at java.awt.Container.dispatchEventImpl(Container.java:2278)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:702)
        at java.awt.EventQueue$3.run(EventQueue.java:696)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDo
main.java:75)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDo
main.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:724)
        at java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDo
main.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThre
ad.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by csnyulas** [comment]
Sorry for this. Would it be possible to take a look at the spreadsheet? Maybe we can identify the problem.

I guess what is happening is that you have a some columns that have numbers in the first row(s), which makes the Spreadsheet API interpret that column as containing a numeric value, but in some of the subsequent rows there is a non-numeric value in a that column. If you identify the problematic column, you may be able to avoid this problem by explicitly setting the cell type to text, in MS Excel (or fixing the problematic cell, if it is a typo).

We should add some more detailed logging information (for example if logging level is set to DEBUG), that would show which cell is currently processed.

**Comment by Evertude** [comment]
Thank you for the quick response. I solved the problem with some trial and error but I can't tell you what exactly caused the problem because the file has about 50k lines and several sheets.

Huge files also cause a GC exception if you have the maximum ram size limited to 500M (default I think). Would be nice to also have a note that says you should adapt the -Xmx parameter of the JVM (I need about 10G for the file)
