### ISSUE TITLE
Exception when "deselecting" a cell of a selected column/row using CTRL+click 

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/cellfie-plugin#92]
If I select a column and then I try to deselect a cell (for example the one in the first row), with CTRL+click, I get this exception: 

```
Uncaught Exception in thread 'AWT-EventQueue-0' 
java.lang.ArrayIndexOutOfBoundsException: 0
    at org.mm.cellfie.ui.view.SheetPanel$1.mouseReleased(SheetPanel.java:50) ~[na:na]
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290) ~[na:1.8.0_40]
    at java.awt.Component.processMouseEvent(Component.java:6525) ~[na:1.8.0_40]
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[na:1.8.0_40]
    at java.awt.Component.processEvent(Component.java:6290) ~[na:1.8.0_40]
    at java.awt.Container.processEvent(Container.java:2234) ~[na:1.8.0_40]
    at java.awt.Component.dispatchEventImpl(Component.java:4881) ~[na:1.8.0_40]
    at java.awt.Container.dispatchEventImpl(Container.java:2292) ~[na:1.8.0_40]
    at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898) ~[na:1.8.0_40]
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533) ~[na:1.8.0_40]
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462) ~[na:1.8.0_40]
    at java.awt.Container.dispatchEventImpl(Container.java:2278) ~[na:1.8.0_40]
    at java.awt.Window.dispatchEventImpl(Window.java:2750) ~[na:1.8.0_40]
    at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751) ~[na:1.8.0_40]
    at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_40]
    at java.awt.EventQueue$3.run(EventQueue.java:702) ~[na:1.8.0_40]
    at java.awt.EventQueue$3.run(EventQueue.java:696) ~[na:1.8.0_40]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86) ~[na:1.8.0_40]
    at java.awt.EventQueue$4.run(EventQueue.java:724) ~[na:1.8.0_40]
    at java.awt.EventQueue$4.run(EventQueue.java:722) ~[na:1.8.0_40]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:721) ~[na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]
```

This does not happen if there are multiple columns selected.
The same behaviour can be observed for a single selected row.

In fact the it happens when one CTRL+clicks on any selected range of cells that expends either to only one single column or one single row (e.g. B5:B7, or A2:C2).

**Comment by csnyulas** [comment]
This happens again after these commits:
https://github.com/protegeproject/cellfie-plugin/compare/f77f0ed9f138...046ad7025bfa

This time the exception is this:

```
Uncaught Exception in thread 'AWT-EventQueue-0' 
java.lang.ArrayIndexOutOfBoundsException: 0
    at org.mm.cellfie.ui.view.SheetPanel$SelectCellRange.selectCellRangeOnMouseDragged(SheetPanel.java:193) ~[na:na]
    at org.mm.cellfie.ui.view.SheetPanel$SelectCellRange.mouseReleased(SheetPanel.java:184) ~[na:na]
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290) ~[na:1.8.0_40]
    at java.awt.Component.processMouseEvent(Component.java:6525) ~[na:1.8.0_40]
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[na:1.8.0_40]
    at java.awt.Component.processEvent(Component.java:6290) ~[na:1.8.0_40]
    at java.awt.Container.processEvent(Container.java:2234) ~[na:1.8.0_40]
    at java.awt.Component.dispatchEventImpl(Component.java:4881) ~[na:1.8.0_40]
    at java.awt.Container.dispatchEventImpl(Container.java:2292) ~[na:1.8.0_40]
    at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898) ~[na:1.8.0_40]
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533) ~[na:1.8.0_40]
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462) ~[na:1.8.0_40]
    at java.awt.Container.dispatchEventImpl(Container.java:2278) ~[na:1.8.0_40]
    at java.awt.Window.dispatchEventImpl(Window.java:2750) ~[na:1.8.0_40]
    at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751) ~[na:1.8.0_40]
    at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_40]
    at java.awt.EventQueue$3.run(EventQueue.java:702) ~[na:1.8.0_40]
    at java.awt.EventQueue$3.run(EventQueue.java:696) ~[na:1.8.0_40]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86) ~[na:1.8.0_40]
    at java.awt.EventQueue$4.run(EventQueue.java:724) ~[na:1.8.0_40]
    at java.awt.EventQueue$4.run(EventQueue.java:722) ~[na:1.8.0_40]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:721) ~[na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]
```
